version: '3.4'

services:
  app:
    image: free_01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      SECURE_COOKIE: ${SECURE_COOKIE}
      development: ${development}
      PORT: ${PORT}
    ports:
      - ${PORT}:3000
  mongo:
    image: mongo
